version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7
    restart: always
    env_file: .env
    networks:
      - app-network

  nestjs:
    container_name: nestjs
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
